FROM eclipse-temurin:25-jre

WORKDIR /app
COPY ssl-service/target/ssl-service-*.jar /app/app.jar
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
